// <auto-generated />
using System;
using JalgrattaEksamMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JalgrattaEksamMVC.Migrations
{
    [DbContext(typeof(JalgrattaeksamContext))]
    partial class JalgrattaeksamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JalgrattaEksamMVC.Models.Jalgrattaeksam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Eesnimi")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("eesnimi");

                    b.Property<int?>("Luba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luba")
                        .HasDefaultValueSql("((-1))");

                    b.Property<string>("Perekonnanimi")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("perekonnanimi");

                    b.Property<int?>("Ringtee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ringtee")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int?>("Slaalom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("slaalom")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int?>("Tanav")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tanav")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int?>("Teooriatulemus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teooriatulemus")
                        .HasDefaultValueSql("((-1))");

                    b.HasKey("Id");

                    b.ToTable("jalgrattaeksam");
                });
#pragma warning restore 612, 618
        }
    }
}
